version: "3.7"
services:
  github-runner:
    build: .
    image: homecentr/github-runner
    restart: unless-stopped
    environment:
      GH_OWNER: homecentr
      GH_TOKEN: ${GH_TOKEN}
      RUNNER_NAME: "Test runner"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock